// A000029 — necklaces with n beads of 2 colors, allowing turning over (also called bracelets).
//
// IMPLEMENTATION. Computes a(n) from the definition the page draws: enumerate every binary string
// of length n as a point in {0,1}^n, and count ORBITS under the group generated by rotation and
// reflection (the dihedral group D_n acting on bead positions) — two strings are the same bracelet
// exactly when one reaches the other by rotating and/or flipping. No table of published terms is
// consulted.
//
// Run:  node sequences/A000029/solution.mjs [maxN]        (default 20)
//
// Method: a direct orbit search, not a formula. Walk every unvisited string, flood-fill its whole
// orbit by repeatedly applying "rotate by 1" and "reverse" until nothing new appears, mark every
// string found, and count one orbit per flood-fill. This is the definition itself, not Burnside's
// lemma — the independent check in proof.mjs is what applies Burnside's lemma, from scratch, as a
// genuinely different method to cross-check this one against.
//
// Cost: exponential in n (2^n strings), same shape as A000001/A100001's walls, not a polynomial
// count. Measured on this machine: n=20 in 45 ms (27,012 orbits), n=24 in 679 ms (352,698 orbits),
// n=27 in 8.5 s (2,493,726 orbits); n=28 needs a 2^28-byte (256 MB) array and was not run — the
// wall here is memory for the visited-set, not search time.

function rotateBy1(s, n) {
  return ((s << 1) | (s >>> (n - 1))) & ((1 << n) - 1);
}

function reverseBits(s, n) {
  let r = 0;
  for (let i = 0; i < n; i++) r |= ((s >>> i) & 1) << (n - 1 - i);
  return r;
}

// Every orbit under rotation + reflection, as its full member list (used by the page to draw one
// orbit's actual strings) plus the total count.
export function bracelets(n) {
  if (n === 0) return { count: 1, orbits: [[0]] };
  const size = 1 << n;
  const seen = new Uint8Array(size);
  const orbits = [];
  for (let s = 0; s < size; s++) {
    if (seen[s]) continue;
    const members = [];
    const stack = [s];
    seen[s] = 1;
    while (stack.length) {
      const cur = stack.pop();
      members.push(cur);
      const r = rotateBy1(cur, n);
      const f = reverseBits(cur, n);
      if (!seen[r]) { seen[r] = 1; stack.push(r); }
      if (!seen[f]) { seen[f] = 1; stack.push(f); }
    }
    orbits.push(members);
  }
  return { count: orbits.length, orbits };
}

export function a(n) {
  return bracelets(n).count;
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const maxN = Number(process.argv[2] || 20);
  const out = [];
  for (let n = 0; n <= maxN; n++) {
    const t0 = Date.now();
    const v = a(n);
    out.push(v);
    console.log(`a(${n}) = ${v}   (${Date.now() - t0} ms)`);
  }
  console.log('\n' + out.join(', '));
}
