// A000003 — number of classes of primitive positive definite binary quadratic forms
// ax² + bxy + cy² of discriminant D = -4n (equivalently, the class number of the quadratic order
// of discriminant -4n).
//
// IMPLEMENTATION. Computes a(n) from first principles, by the same procedure the page explains:
// enumerate every REDUCED primitive positive-definite form of discriminant D = -4n directly. No
// table of known class numbers is consulted.
//
// Run:  node sequences/A000003/solution.mjs [maxN]        (default 30)
//
// Method — classical Lagrange–Gauss reduction theory
//   Every form ax²+bxy+cy² with a>0 and D=b²-4ac<0 (positive definite) is SL(2,Z)-equivalent to
//   exactly one REDUCED form, meaning -a < b ≤ a ≤ c, with the extra rule b ≥ 0 whenever a = c
//   (this rule alone kills the one remaining duplicate — the a ≠ c case never double-counts
//   because b = -a is never generated by the loop's own range, see below). Counting classes of
//   discriminant D is therefore exactly counting these reduced triples, an idea going back to
//   Gauss's "Disquisitiones Arithmeticae" §171 and standard since (e.g. Cox, "Primes of the Form
//   x² + ny²", ch. 2).
//
//   For a reduced form, 4ac - b² = |D| and b² ≤ a² ≤ ac give 3a² ≤ 4ac - b² = |D|, so a is bounded:
//   a ≤ sqrt(|D|/3). That bound is what makes the search finite and turns "count the classes" into
//   a direct enumeration:
//     for a = 1 .. floor(sqrt(|D|/3)):
//       for b = -a+1 .. a:                      (never b = -a — see the note above)
//         c = (b² - D) / (4a), keep only if that's a positive integer and c ≥ a
//         skip if a = c and b < 0                (the one remaining duplicate: (a,b,a) ~ (a,-b,a))
//         keep only if gcd(a,b,c) = 1             (primitivity)
//
// Cost: this is polynomial, not a combinatorial search — there is no explosion the way A000001's
// group count or A100001's configuration count have one. Measured on this machine, computing every
// a(1)..a(maxN) in one pass: maxN=1,000 in 6 ms, maxN=10,000 in 166 ms, maxN=100,000 in 14.3 s (the
// per-n cost itself stays O(√n); the total for a full prefix grows like maxN^1.5 because every
// smaller n is recomputed on the way there) — nowhere close to a wall at any n a page would draw.

function gcd(x, y) {
  x = Math.abs(x); y = Math.abs(y);
  while (y) { [x, y] = [y, x % y]; }
  return x;
}

// Every reduced primitive positive-definite form of discriminant D = -4n, as [a, b, c] triples.
export function reducedForms(n) {
  const D = -4 * n;
  const aMax = Math.floor(Math.sqrt(-D / 3));
  const forms = [];
  for (let a = 1; a <= aMax; a++) {
    for (let b = -a + 1; b <= a; b++) {
      const num = b * b - D;
      if (num % (4 * a) !== 0) continue;
      const c = num / (4 * a);
      if (c < a) continue;
      if (a === c && b < 0) continue;
      if (gcd(gcd(a, b), c) !== 1) continue;
      forms.push([a, b, c]);
    }
  }
  return forms;
}

export function a(n) {
  return reducedForms(n).length;
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  const maxN = Number(process.argv[2] || 30);
  const out = [];
  const t0 = Date.now();
  for (let n = 1; n <= maxN; n++) out.push(a(n));
  const ms = Date.now() - t0;
  console.log(`a(1..${maxN}) computed in ${ms} ms`);
  console.log('\n' + out.join(', '));
}
